apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.carSimulator.name }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
  name: {{ .Values.carSimulator.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.carSimulator.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.carSimulator.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.carSimulator.name }}
      name: {{ .Values.carSimulator.name }}
    spec:
      volumes:
        - name: config
          configMap:
            name: car-simulator-us-routes-config
            defaultMode: 420
      containers:
      - name: {{ .Values.carSimulator.name }}
        image: quay.io/bobbycar/car-simulator:1.1.1
        imagePullPolicy: Always
        volumeMounts:
            - name: config
              readOnly: true
              mountPath: /opt/routes
        env:
            - name: com.redhat.bobbycar.carsim.route
              value: '/opt/routes'
            - name: com.redhat.bobbycar.carsim.cars
              value: {{ .Values.carSimulator.config.carsimCars | quote }}
            - name: com.redhat.bobbycar.carsim.factor
              value: {{ .Values.carSimulator.config.carsimFactor | quote }}
            - name: com.redhat.bobbycar.carsim.repeat
              value: {{ .Values.carSimulator.config.carsimRepeat | quote }}
            - name: quarkus.log.level
              value: 'INFO'
            - name: com.redhat.bobbycar.carsim.delay
              value: {{ .Values.carSimulator.config.carsimDelay | quote }}
            - name: mp.messaging.incoming.zonechange.type
              value: 'smallrye-mqtt'
            - name: mp.messaging.incoming.zonechange.topic
              value: {{ .Values.mqtt.topic.mqttZoneChangeTopic | quote }}
            - name: mp.messaging.incoming.zonechange.host
              value: 'bobbycar-amq-mqtt-all-0-svc'
            - name: mp.messaging.incoming.zonechange.port
              value: '61616'
            - name: com.redhat.bobbycar.carsim.datagrid.url
              value: 'http://cache-service-{{ .Values.namespace }}.{{ .Values.ocpDomain }}'
            - name: com.redhat.bobbycar.carsim.kafka.url
              value: 'http://bobbycar-{{ .Values.namespace }}.{{ .Values.ocpDomain }}'
            - name: mp.messaging.outgoing.enginemetrics.type
              value: 'smallrye-mqtt'
            - name: mp.messaging.outgoing.enginemetrics.topic
              value: {{ .Values.mqtt.topic.mqttMetricsTopic | quote }}
            - name: mp.messaging.outgoing.enginemetrics.host
              value: 'bobbycar-amq-mqtt-all-0-svc'
            - name: mp.messaging.outgoing.enginemetrics.port
              value: '61616'
            - name: mp.messaging.incoming.ota-updates.host
              value: 'bobbycar-amq-mqtt-all-0-svc'
            - name: mp.messaging.incoming.ota-updates.port
              value: '61616'
            - name: mp.messaging.incoming.ota-updates.topic
              value: 'ota/+'
            - name: mp.messaging.incoming.ota-updates.type
              value: 'smallrye-mqtt'
            - name: quarkus.http.cors
              value: 'true'
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        envFrom:
          - configMapRef: 
              name: car-simulator-us-routes-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30