kind: Secret
apiVersion: v1
metadata:
  name: kafka2datagrid
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.dg.car.snapshot.cacheName: {{ .Values.datagrid.cache.snapshot }}
    com.redhat.bobbycar.camelk.dg.car.cacheName: {{ .Values.datagrid.cache.car }}
    com.redhat.bobbycar.camelk.dg.zone.cacheName: {{ .Values.datagrid.cache.zone }}
    com.redhat.bobbycar.camelk.dg.refresh.interval: {{ .Values.datagrid.cache.refresh.interval }}
    com.redhat.bobbycar.camelk.dg.host: bobbycar-dg
    com.redhat.bobbycar.camelk.dg.password: {{ .Values.datagrid.account.password }}
    com.redhat.bobbycar.camelk.dg.user: {{ .Values.datagrid.account.user }}
    com.redhat.bobbycar.camelk.kafka.brokers: {{ .Values.kafka.bootstrap.servers }}
    com.redhat.bobbycar.camelk.kafka.topic: {{ .Values.kafka.topic.gps }}
    com.redhat.bobbycar.camelk.mqtt.brokerUrl: tcp://bobbycar-amq-mqtt-all-0-svc:61616
    com.redhat.bobbycar.camelk.mqtt.topic: {{ .Values.mqtt.topic.mqttZoneChangeTopic }}
    com.redhat.bobbycar.camelk.dg.ocp.api: {{ .Values.ocpApi }}
    com.redhat.bobbycar.camelk.dg.namespace: {{ .Values.namespace }}
type: Opaque

    
