kind: Secret
apiVersion: v1
metadata:
  name: weather-service-secret
stringData:
    apiKey: {{ .Values.weatherService.owm.api.key }}
    ibmApiKey: {{ .Values.weatherService.ibm.api.key }}
type: Opaque