kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: weather-service
  namespace: {{ .Values.namespace }}
  labels:
    app: weather-service
spec:
  host: weather-service-{{ .Values.namespace }}.{{ .Values.ocpDomain }}
  to:
    kind: Service
    name: weather-service
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None