apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: bobbycar-cluster
  namespace: {{ .Values.namespace }}
spec:
  kafka:
    replicas: {{ .Values.kafka.cluster.brokerReplicas }}
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    - name: external
      port: 9094
      tls: true
      type: route
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    storage:
      type: ephemeral 
  zookeeper:
    replicas: {{ .Values.kafka.cluster.zookeeperReplicas }}
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}